
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\Maissen Belgacem\Desktop\Python\tkinter widgets\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1250x670")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 670,
    width = 1250,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    174.0,
    0.0,
    1250.0,
    670.0,
    fill="#D7D9E5",
    outline="")

canvas.create_rectangle(
    0.0,
    0.0,
    174.0,
    670.0,
    fill="#222222",
    outline="")

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=12.0,
    y=613.0,
    width=151.0,
    height=36.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=12.0,
    y=130.0,
    width=151.0,
    height=36.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=12.0,
    y=72.0,
    width=151.0,
    height=36.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=12.0,
    y=14.0,
    width=151.0,
    height=36.0
)

canvas.create_rectangle(
    186.0,
    14.0,
    1239.0,
    659.0,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    843.0,
    451.0,
    1222.0,
    552.0,
    fill="#9597A8",
    outline="")

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_5 clicked"),
    relief="flat"
)
button_5.place(
    x=1183.0,
    y=457.0,
    width=30.0,
    height=30.0
)

canvas.create_rectangle(
    843.0,
    338.0,
    1222.0,
    439.0,
    fill="#9597A8",
    outline="")

canvas.create_rectangle(
    843.0,
    223.0,
    1222.0,
    324.0,
    fill="#9597A8",
    outline="")

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    1035.0,
    284.5,
    image=entry_image_1
)
entry_1 = Text(
    bd=0,
    bg="#9597A8",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=857.0,
    y=250.0,
    width=356.0,
    height=67.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    1035.0,
    400.5,
    image=entry_image_2
)
entry_2 = Text(
    bd=0,
    bg="#9597A8",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=857.0,
    y=366.0,
    width=356.0,
    height=67.0
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    1035.0,
    519.5,
    image=entry_image_3
)
entry_3 = Text(
    bd=0,
    bg="#9597A8",
    fg="#000716",
    highlightthickness=0
)
entry_3.place(
    x=857.0,
    y=494.0,
    width=356.0,
    height=49.0
)

canvas.create_text(
    857.0,
    227.0,
    anchor="nw",
    text="Entry’s Title :",
    fill="#000000",
    font=("Inter", 15 * -1)
)

canvas.create_text(
    857.0,
    343.0,
    anchor="nw",
    text="Entry’s Summary :",
    fill="#000000",
    font=("Inter", 15 * -1)
)

canvas.create_text(
    857.0,
    463.0,
    anchor="nw",
    text="Recent Hashtags :",
    fill="#000000",
    font=("Inter", 15 * -1)
)

canvas.create_text(
    211.0,
    29.0,
    anchor="nw",
    text="From : Example (15 entries)",
    fill="#000000",
    font=("Inter", 14 * -1)
)

canvas.create_text(
    211.0,
    48.0,
    anchor="nw",
    text="Feed : Some title here!",
    fill="#000000",
    font=("Inter", 20 * -1)
)

canvas.create_rectangle(
    211.0,
    83.0,
    801.0,
    621.0,
    fill="#008F0E",
    outline="")

button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_6 clicked"),
    relief="flat"
)
button_6.place(
    x=843.0,
    y=575.0,
    width=182.0,
    height=46.0
)

button_image_7 = PhotoImage(
    file=relative_to_assets("button_7.png"))
button_7 = Button(
    image=button_image_7,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_7 clicked"),
    relief="flat"
)
button_7.place(
    x=1040.0,
    y=575.0,
    width=182.0,
    height=46.0
)

canvas.create_rectangle(
    843.0,
    37.0,
    1222.0,
    209.0,
    fill="#EAFF00",
    outline="")
window.resizable(False, False)
window.mainloop()

