
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\Maissen Belgacem\Desktop\Python\tkinter widgets\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1250x670")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 670,
    width = 1250,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    174.0,
    0.0,
    1250.0,
    670.0,
    fill="#D7D9E5",
    outline="")

canvas.create_rectangle(
    0.0,
    0.0,
    174.0,
    670.0,
    fill="#222222",
    outline="")

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=12.0,
    y=613.0,
    width=151.0,
    height=36.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=12.0,
    y=152.0,
    width=151.0,
    height=36.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=12.0,
    y=83.0,
    width=151.0,
    height=36.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=12.0,
    y=14.0,
    width=151.0,
    height=36.0
)

canvas.create_rectangle(
    186.0,
    14.0,
    1239.0,
    659.0,
    fill="#FF0000",
    outline="")

canvas.create_text(
    582.0,
    39.0,
    anchor="nw",
    text="Posts in Queue",
    fill="#000000",
    font=("Inter", 36 * -1)
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_5 clicked"),
    relief="flat"
)
button_5.place(
    x=622.0,
    y=590.0,
    width=182.0,
    height=46.0
)

canvas.create_rectangle(
    1108.0,
    106.0,
    1122.0,
    549.0,
    fill="#FF8900",
    outline="")

canvas.create_rectangle(
    330.0,
    106.0,
    1096.0,
    549.0,
    fill="#FF00F4",
    outline="")

canvas.create_rectangle(
    344.0,
    121.0,
    1080.0,
    251.0,
    fill="#DBFF00",
    outline="")

button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_6 clicked"),
    relief="flat"
)
button_6.place(
    x=1041.0,
    y=130.0,
    width=30.0,
    height=30.0
)

button_image_7 = PhotoImage(
    file=relative_to_assets("button_7.png"))
button_7 = Button(
    image=button_image_7,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_7 clicked"),
    relief="flat"
)
button_7.place(
    x=999.0,
    y=130.0,
    width=30.0,
    height=30.0
)

button_image_8 = PhotoImage(
    file=relative_to_assets("button_8.png"))
button_8 = Button(
    image=button_image_8,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_8 clicked"),
    relief="flat"
)
button_8.place(
    x=957.0,
    y=130.0,
    width=30.0,
    height=30.0
)

canvas.create_text(
    528.0,
    223.0,
    anchor="nw",
    text="18-Oct-2024",
    fill="#606060",
    font=("Inter", 14 * -1)
)

canvas.create_text(
    531.0,
    161.0,
    anchor="nw",
    text="Here’s some description\nsdfqdfjqlsdkfjqlm sjdfozijf paoizj foaie^àsdfjm qkdsjf^oaijfîjfîojfsdfkjq m",
    fill="#606060",
    font=("Inter", 15 * -1)
)

canvas.create_text(
    531.38330078125,
    130.0,
    anchor="nw",
    text="Post title",
    fill="#000000",
    font=("Inter", 20 * -1)
)

canvas.create_rectangle(
    355.4512023925781,
    130.0,
    519.9321136474609,
    240.0,
    fill="#0019FF",
    outline="")
window.resizable(False, False)
window.mainloop()

